### PR TITLE
Changes the design to take advantage of PDUI.

### PR DESCRIPTION
**Pull request by xcambar**
Lost features: Categories, list by authors, blog roll (whatever that is)

@nlhkabu I've copy/pasted the necessary PDUI files.

Here are the screenshots to illustrate the changes:

# Index page

screenshot-2018-1-23 novapost s paradize 1

# Article page

screenshot-2018-1-23 timescaledb

### CODE REVIEW

**Comment by aRkadeFR** [comment]
We will loose the categories? I think couple of people follow the blogpost for only certain categories.
At the same time, I like PDUI very much and see this change as an improvement 👍

**Comment by nlhkabu** [comment]
hi @xcambar - this is great, thank you :)

A few things:

- I think we can use a card header for each article, instead of a <hr>
- We can probably include the categories in the sidebar, and use `affix` to keep it sticky - wdyt?
- We should write some custom css to style code blocks and `<pre>` tags, as this is not currently supported in PDUI

If you like, I can make these changes directly on your branch?  Or if you'd prefer to make the changes, I can review again later?

**Comment by xcambar** [comment]
As no one really expressed concerns about the categories, I'd really like to see this PR merged as is (as it seems to be considered an improvement enough) after which you'll be able to do the changes as and when you see fit.

**Comment by xcambar** [comment]
As per @nlhkabu agreement (discussed on Slack), this can be merged.

**Pull request merged**
